Add current time to quote
blockchain/bitcoin-exchange-client pull request #5
Opened 2017-04-20 18:23 UTC by plondon

2017-04-21 07:48 UTC, Sjors requested changes
This is in the frontend at the moment:
```js
let timeToExpiration = new Date(quote.expiresAt) - new Date(quote.timeOfRequest) - 1000
```
Can you add a `timeToExpiration`property to bitcoin-exchange client?

Can you also default `_timeOfRequest` to the current system time? That way it will work for all partners without having to modify them immediately.

2017-04-21 18:57 UTC, plondon commented
Added timeToExpiration

2017-04-22 08:08 UTC, Sjors commented on src/quote.js
> +  get timeToExpiration () { return this._timeToExpiration; }
`timeToExpiration` should calculated in the getter...

2017-04-22 08:10 UTC, Sjors commented on src/quote.js
> +  get timeOfRequest () { return this._timeOfRequest || new Date().getTime(); }
This doesn't make sense. `quote.timeOfRequest` would just return the current time all the time.

I would set `this._timeOfRequest = new Date().getTime()` in the quote constructor. That will be overridden in SFOX subclass.

2017-04-24 12:42 UTC, Sjors approved these changes

2017-04-24 12:43 UTC, merged